HOST = "127.0.0.1"

SPLITTER_PORT = "50100"
REDUCER_PORTS = ("50110", "50111")

MAPPER_IDS = ("1", "2", "3")
REDUCER_IDS = tuple(range(len(REDUCER_PORTS)))

MAPPER_COUNT = len(MAPPER_IDS)
REDUCER_COUNT = len(REDUCER_IDS)

END_OF_TEXT = "__END_OF_TEXT__"

